// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    pixel_canvas_contract
    (
        init => init
        upgrade => upgrade
        buyPixels => buy_pixels
        consumeCredits => consume_credits
        setCharityAddress => set_charity_address_endpoint
        getPaintingCredits => get_painting_credits
        getCharityAddress => get_charity_address
        getTotalDonated => get_total_donated
        getBurnAddress => get_burn_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
