// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           25
// Async Callback (empty):               1
// Total number of exported functions:  28

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    pixel_canvas_contract
    (
        init => init
        upgrade => upgrade
        setPixelToken => set_pixel_token
        setCharityAddress => set_charity_address_endpoint
        setEpochDuration => set_epoch_duration
        setEpochCharities => set_epoch_charities
        vote => vote
        startEpoch => start_epoch
        endEpoch => end_epoch
        buyPixels => buy_pixels
        paintPixels => paint_pixels
        distributePixelToCharity => distribute_pixel_to_charity
        getPixelOwner => get_pixel_owner
        getPixelTokenId => get_pixel_token_id
        getPixelDenomination => get_pixel_denomination
        getTotalPixelForCharity => get_total_pixel_for_charity
        getCharityAddress => get_charity_address
        getTotalDonated => get_total_donated
        getCurrentEpoch => get_current_epoch
        getEpochStartTimestamp => get_epoch_start_timestamp
        getEpochDuration => get_epoch_duration
        getEpochTopPainter => get_epoch_top_painter
        getEpochPixelCount => get_epoch_pixel_count
        getEpochCharities => get_epoch_charities
        getVoteTallies => get_vote_tallies
        getMyVote => get_my_vote
        getTotalEgldForCharity => get_total_egld_for_charity
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
